version: '3'

services:
  php-nginx:
    depends_on:
      - db
    links:
      - db
    build:
      context: .
    volumes:
      - ./code:/var/www/html
      - ./.docker/site.conf:/etc/nginx/conf.d/default.conf
    command: bash -c "chown -R www-data:www-data /var/www 
            && service nginx start 
            && service php7.2-fpm start 
            && /bin/bash"
    stdin_open: true
    tty: true
    ports:
      - 80:80
  db:
    container_name: postgre-greenwich
    image: kartoza/postgis:11.0-2.5
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASS=master
      - POSTGRES_DBNAME=greenwich
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - ./.docker/postgre:/var/lib/postgresql/data
    ports:
      - 45432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db:db
  redis:
    container_name: redis-greenwich
    image: redis
    volumes:
      - ./redis-data:/data
    ports:
      - 6321:6379
