version: '3'

services:
  php-nginx:
    depends_on:
      - db
    links:
      - db
    build:
      context: .
    volumes:
      - ./code:/var/www/html
      - ./.docker/site.conf:/etc/nginx/conf.d/default.conf
    command: bash -c "chown -R www-data:www-data /var/www 
            && service nginx start 
            && service php7.2-fpm start 
            && /bin/bash"
    stdin_open: true
    tty: true
    ports:
      - 80:80
    networks:
      uranus_api:
        ipv4_address: 110.10.0.10
  db:
    container_name: postgre
    image: kartoza/postgis:11.0-2.5
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASS=master
      - POSTGRES_DBNAME=uranus
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - ./.docker/postgre:/var/lib/postgresql/data
    ports:
      - 35432:5432
    networks:
      uranus_api:
        ipv4_address: 110.10.0.11
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db:db
    networks:
      uranus_api:
        ipv4_address: 110.10.0.13
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./redis-data:/data
    ports:
      - "127.0.0.1:6321:6379"
    networks:
      uranus_api:
        ipv4_address: 110.10.0.12
networks:
  uranus_api:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 110.10.0.0/24
